apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: rag-applications
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: inference
            path: "/workspace/infra/manifests/inference"
            destNamespace: inference
          - name: qdrant
            path: "/workspace/infra/manifests/qdrant"
            destNamespace: qdrant
          - name: rag
            path: "/workspace/infra/manifests/rag"
            destNamespace: rag
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: "https://github.com/Athithya-Sakthivel/RAG8s.git"
        targetRevision: "main"
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{destNamespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
