{
 "title": "Platform Overview",
 "panels": [
  {
   "title": "Total discovery (pods)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max(vm_promscrape_discovery_kubernetes_objects{role=\"pod\"})"
    }
   ]
  },
  {
   "title": "Services not ready (count)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
   "targets": [
    { "expr": "count(service_ready==0)" }
   ]
  },
  {
   "title": "vmagent scrape pool targets (up/down)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "vm_promscrape_scrape_pool_targets"
    }
   ]
  }
 ]
}