apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: inference
  labels: &id001
    app.kubernetes.io/name: frontend
spec:
  replicas: 3
  selector:
    matchLabels: *id001
  template:
    metadata:
      labels: *id001
    spec:
      serviceAccountName: frontend-sa
      containers:
      - name: frontend
        image: athithya5354/frontend-and-auth:v5
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: frontend-config
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 5
          timeoutSeconds: 1
          failureThreshold: 3
