apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: inference
spec:
  replicas: 1
  selector:
    matchLabels: &id001
      app.kubernetes.io/name: frontend
  template:
    metadata:
      labels: *id001
      annotations:
        frontend/config-checksum: f91d935c2155fddb268b68389c9e9e5750d2778685b858bc880a5899d9b4a8ef
    spec:
      serviceAccountName: frontend-sa
      containers:
      - name: frontend
        image: athithya5354/frontend-and-auth:v12
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: frontend-config
        env:
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: frontend-secret
              key: JWT_SECRET
        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: frontend-secret
              key: SESSION_SECRET
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /orchestrator/health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /orchestrator/health
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 5
          timeoutSeconds: 1
