replicaCount: 1
image:
  repository: qdrant/qdrant
  tag: v1.16.0
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
p2p:
  port: 6335
cluster:
  enabled: true
  peers:
  - http://qdrant-0.qdrant-headless:6335
snapshots:
  enabled: false
  s3:
    bucket: ''
    endpoint: ''
    region: ''
    prefix: ''
extraEnv:
- name: AZURE_STORAGE_CONNECTION_STRING
  valueFrom:
    secretKeyRef:
      name: qdrant-backup-azure
      key: AZURE_STORAGE_CONNECTION_STRING
- name: AZURE_STORAGE_ACCOUNT_NAME
  valueFrom:
    secretKeyRef:
      name: qdrant-backup-azure
      key: AZURE_STORAGE_ACCOUNT_NAME
- name: AZURE_STORAGE_ACCOUNT_KEY
  valueFrom:
    secretKeyRef:
      name: qdrant-backup-azure
      key: AZURE_STORAGE_ACCOUNT_KEY
- name: QDRANT__SERVICE__API_KEY
  valueFrom:
    secretKeyRef:
      name: qdrant-service-creds
      key: QDRANT__SERVICE__API_KEY
resources:
  requests:
    cpu: '1'
    memory: 2Gi
  limits:
    cpu: '1'
    memory: 2Gi
tolerations: []
persistence:
  enabled: true
  storageClass: standard
  size: 50Gi
config:
  params:
    shard_number: 1
    replication_factor: 1
    write_consistency_factor: 1
  log_level: INFO
  storage:
    storage_path: /qdrant/storage
    snapshots_path: /qdrant/snapshots
