replicaCount: 1
image:
  repository: qdrant/qdrant
  tag: v1.16.0
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  labels:
    app.kubernetes.io/name: qdrant
    app.kubernetes.io/component: qdrant
podAnnotations:
  monitoring.io/scrape: 'true'
  monitoring.io/port: '6333'
  monitoring.io/path: /metrics
  qdrant/config-checksum: 64b8b562c6926ef587b63410d96fc47a6a4a4b7134b0be3b65e18ab739e95e00
ports:
- name: metrics
  containerPort: 6333
  protocol: TCP
p2p:
  port: 6335
cluster:
  enabled: true
  peers:
  - http://qdrant-0.qdrant-headless:6335
snapshots:
  enabled: false
  s3:
    bucket: ''
    endpoint: ''
    region: ''
    prefix: ''
extraEnv: []
resources:
  requests:
    cpu: '1'
    memory: 2Gi
  limits:
    cpu: '1'
    memory: 2Gi
tolerations: []
persistence:
  enabled: false
  size: 20Gi
  storageClass: ''
config:
  on_disk_payload: false
  log_level: INFO
  storage:
    storage_path: /qdrant/storage
    snapshots_path: /qdrant/snapshots
hnsw_defaults:
  on_disk: false
