apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy-google-svc
  namespace: auth
  labels:
    app.kubernetes.io/name: oauth2-proxy
    app.kubernetes.io/component: auth
    app.kubernetes.io/managed-by: gen_oauth2proxy
    env: staging
    app.kubernetes.io/instance: oauth2-proxy-google
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 4180
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/instance: oauth2-proxy-google
