{{- if .Values.karpenter.enabled }}
{{- $ns := .Values.karpenter.namespace | default "karpenter-cpu" }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $ns }}
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: {{ .Values.karpenter.ec2NodeClass.name }}
  namespace: {{ $ns }}
spec:
  amiFamily: {{ .Values.karpenter.ec2NodeClass.amiFamily | default "AL2" }}
  {{- if .Values.karpenter.ec2NodeClass.amiID }}
  amiID: {{ .Values.karpenter.ec2NodeClass.amiID | quote }}
  {{- else if .Values.karpenter.ec2NodeClass.amiSelector }}
  amiSelector:
    {{- toYaml .Values.karpenter.ec2NodeClass.amiSelector | nindent 4 }}
  {{- end }}
  subnetSelector:
    {{- toYaml .Values.karpenter.ec2NodeClass.subnetSelector | nindent 4 }}
  securityGroupSelector:
    {{- toYaml .Values.karpenter.ec2NodeClass.securityGroupSelector | nindent 4 }}
  role: {{ .Values.karpenter.ec2NodeClass.instanceProfile | quote }}
  blockDeviceMappings:
    {{- toYaml .Values.karpenter.ec2NodeClass.blockDeviceMappings | nindent 2 }}
  tags:
    {{- toYaml .Values.karpenter.ec2NodeClass.tags | nindent 4 }}
---
{{- $common := .Values.karpenter.common }}
{{- $req := $common.requirements }}
{{- range $i, $pool := .Values.karpenter.nodePools }}
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: {{ $pool.name }}
  namespace: {{ $ns }}
spec:
  template:
    metadata:
      labels:
        {{- toYaml $common.labels | nindent 8 }}
    spec:
      taints:
        {{- toYaml $common.taints | nindent 8 }}
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: {{ $.Values.karpenter.ec2NodeClass.name }}
      requirements:
        - key: "karpenter.k8s.aws/instance-family"
          operator: In
          values:
          {{- range $req.instanceFamilies }}
            - "{{ . }}"
          {{- end }}
        - key: "karpenter.k8s.aws/instance-size"
          operator: In
          values:
          {{- range $req.instanceSizes }}
            - "{{ . }}"
          {{- end }}
        - key: "kubernetes.io/arch"
          operator: In
          values:
          {{- range $req.architectures }}
            - "{{ . }}"
          {{- end }}
        - key: "karpenter.sh/capacity-type"
          operator: In
          values:
            - "{{ $pool.capacityType }}"
        {{- if $req.zones }}
        - key: "topology.kubernetes.io/zone"
          operator: In
          values:
          {{- range $req.zones }}
            - "{{ . }}"
          {{- end }}
        {{- end }}
  disruption:
    consolidationPolicy: {{ $common.disruption.consolidationPolicy | default "WhenEmptyOrUnderutilized" }}
    consolidateAfter: {{ $common.disruption.consolidateAfter | default "60s" | quote }}
    expireAfter: {{ $common.disruption.expireAfter | default "72h" | quote }}
  limits:
    resources:
      {{- toYaml $common.limits.resources | nindent 6 }}
---
{{- end }}
{{- end }}
