apiVersion: v1
kind: ConfigMap
metadata:
  name: retrieval-config
  namespace: inference
  labels:
    app.kubernetes.io/name: retrieval
    app.kubernetes.io/component: inference
    app.kubernetes.io/managed-by: retriever-generator
    app.kubernetes.io/instance: retrieval
    env: staging
data:
  COLLECTION_NAME: default_rag_collection1
  HTTP_TIMEOUT: '10.0'
  DENSE_DIM: '384'
  MAX_CHUNKS_TO_LLM: '6'
  LLM_MODEL: llama-3.1-8b-instant
  LLM_MAX_TOKENS: '512'
  LLM_TEMPERATURE: '0.0'
  RERANKER_MODE: AUTO
  RERANK_TOPK: '20'
  AZURE_STORAGE_ACCOUNT_NAME: defaultsa515
  AZURE_ENDPOINT_SUFFIX: core.windows.net
