apiVersion: v1
kind: Service
metadata:
  name: retrieval
  namespace: inference
  labels:
    app.kubernetes.io/name: retrieval
spec:
  selector:
    app.kubernetes.io/name: retrieval
  ports:
    - name: metrics
      port: 8001
      targetPort: 8001
  type: ClusterIP
