apiVersion: v1
kind: Service
metadata:
  name: retrieval
  namespace: inference
  labels:

    app: 'retrieval'
    team: 'search'
spec:
  selector:

      app: 'retrieval'
      team: 'search'
  ports:
    - name: http
      port: 8001
      targetPort: 8001
  type: ClusterIP