apiVersion: v1
kind: ServiceAccount
metadata:
  name: dense-sa
  namespace: models

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dense-role
  namespace: models
rules:
- apiGroups:
  - ''
  resources:
  - pods
  - services
  - endpoints
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - get
  - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dense-rb
  namespace: models
subjects:
- kind: ServiceAccount
  name: dense-sa
  namespace: models
roleRef:
  kind: Role
  name: dense-role
  apiGroup: rbac.authorization.k8s.io
