# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'grpc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngrpc.proto\x12\x04grpc\"\x1d\n\x0c\x45mbedRequest\x12\r\n\x05texts\x18\x01 \x03(\t\"#\n\rEmbedResponse\x12\x12\n\nembeddings\x18\x01 \x03(\x02\"*\n\rRerankRequest\x12\x19\n\x05pairs\x18\x01 \x03(\x0b\x32\n.grpc.Pair\"\"\n\x04Pair\x12\r\n\x05query\x18\x01 \x01(\t\x12\x0b\n\x03\x64oc\x18\x02 \x01(\t\" \n\x0eRerankResponse\x12\x0e\n\x06scores\x18\x01 \x03(\x02\x32@\n\x0c\x45mbedService\x12\x30\n\x05\x45mbed\x12\x12.grpc.EmbedRequest\x1a\x13.grpc.EmbedResponse2D\n\rRerankService\x12\x33\n\x06Rerank\x12\x13.grpc.RerankRequest\x1a\x14.grpc.RerankResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMBEDREQUEST']._serialized_start=20
  _globals['_EMBEDREQUEST']._serialized_end=49
  _globals['_EMBEDRESPONSE']._serialized_start=51
  _globals['_EMBEDRESPONSE']._serialized_end=86
  _globals['_RERANKREQUEST']._serialized_start=88
  _globals['_RERANKREQUEST']._serialized_end=130
  _globals['_PAIR']._serialized_start=132
  _globals['_PAIR']._serialized_end=166
  _globals['_RERANKRESPONSE']._serialized_start=168
  _globals['_RERANKRESPONSE']._serialized_end=200
  _globals['_EMBEDSERVICE']._serialized_start=202
  _globals['_EMBEDSERVICE']._serialized_end=266
  _globals['_RERANKSERVICE']._serialized_start=268
  _globals['_RERANKSERVICE']._serialized_end=336
# @@protoc_insertion_point(module_scope)
