apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: monitoring
  labels:
    app: alertmanager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
      annotations:
        alerting/alertmanager-config-checksum: baaac1fb0cb5a6c5e5b3e302722d553b7c0bdcf4770dd6eb08fecac03b20bef8
    spec:
      volumes:
      - name: config
        configMap:
          name: alertmanager-config
      containers:
      - name: alertmanager
        image: prom/alertmanager:v0.27.0
        args:
        - --config.file=/etc/alertmanager/alertmanager.yml
        - --storage.path=/alertmanager
        volumeMounts:
        - name: config
          mountPath: /etc/alertmanager
        ports:
        - containerPort: 9093
          name: web
        readinessProbe:
          httpGet:
            path: /api/v2/status
            port: 9093
          initialDelaySeconds: 5
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  selector:
    app: alertmanager
  ports:
  - name: web
    port: 9093
    targetPort: 9093

