apiVersion: apps/v1
kind: Deployment
metadata:
  name: reranker-deployment
  namespace: models
  labels: &id001
    app.kubernetes.io/name: reranker
    app.kubernetes.io/component: reranker
    app.kubernetes.io/managed-by: gen_reranker
    app.kubernetes.io/instance: reranker
    env: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: reranker
  template:
    metadata:
      labels: *id001
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8202'
        prometheus.io/path: /metrics
    spec:
      serviceAccountName: reranker-sa
      containers:
      - name: reranker
        image: athithya5354/reranker:amd64-arm64-v1
        ports:
        - containerPort: 8202
        env:
        - name: RERANKER_PORT
          value: '8202'
        - name: ENV
          value: STAGING
        - name: RERANKER_LOGLEVEL
          value: INFO
        livenessProbe:
          httpGet:
            path: /health
            port: 8202
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 6
        readinessProbe:
          httpGet:
            path: /health
            port: 8202
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8202
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 60
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
