apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: indexer-cron-role
  namespace: indexing
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
