apiVersion: v1
kind: Secret
metadata:
  name: indexer-azure-creds
  namespace: indexing
type: Opaque
stringData:
  AZURE_STORAGE_ACCOUNT_NAME: defaultsa515
  AZURE_STORAGE_CONNECTION_STRING: REPLACE_WITH_REAL_VALUE
