apiVersion: batch/v1
kind: CronJob
metadata:
  name: indexing-backup-cronjob
  namespace: indexing
spec:
  schedule: 0 */6 * * *
  concurrencyPolicy: Allow
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: indexing-backup-cronjob
        spec:
          serviceAccountName: indexer-cron-sa
          restartPolicy: Never
          containers:
          - name: indexer
            image: athithya5354/indexing_pipeline_cpu:v7
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - /opt/venv/bin/python /indexing_pipeline/indexing_pipeline.py
            env:
            - name: AZURE_CHUNKED_PREFIX
              value: data/chunked/
            - name: AZURE_CLIENT_ID
              value: ''
            - name: AZURE_CONTAINER
              value: rag-data-prod
            - name: AZURE_ENDPOINT_SUFFIX
              value: core.windows.net
            - name: AZURE_LOCATION
              value: ''
            - name: AZURE_RESOURCE_GROUP_NAME
              value: ''
            - name: AZURE_SAS_TOKEN
              value: ''
            - name: AZURE_SECRET_NAME
              value: indexer-azure-creds
            - name: AZURE_STORAGE_ACCOUNT_KEY
              value: ''
            - name: AZURE_STORAGE_ACCOUNT_NAME
              value: ''
            - name: AZURE_STORAGE_API_VERSION
              value: '2025-04-01'
            - name: AZURE_STORAGE_CONNECTION_STRING
              value: ''
            - name: AZURE_SUBSCRIPTION_ID
              value: b1e221f4-74ef-4e62-9bca-fb70aef41930
            - name: AZURE_TENANT_ID
              value: b8a65a11-9d1c-4d48-b9f6-dabfc67f2e4b
            - name: AZURE_USE_MANAGED_IDENTITY
              value: '0'
            - name: BATCH_SIZE
              value: '16'
            - name: CSV_TARGET_TOKENS_PER_CHUNK
              value: '600'
            - name: DENSE_DIM
              value: '384'
            - name: DENSE_URL
              value: http://dense-svc.models.svc.cluster.local:8200
            - name: ENV
              value: ''
            - name: EXTRA_SECRET_NAME
              value: indexer-extra-secrets
            - name: HTTP_TIMEOUT
              value: '60'
            - name: IMAGE_MIN_IMG_SIZE_BYTES
              value: '3072'
            - name: IMAGE_OCR_ENGINE
              value: rapidocr
            - name: IMAGE_RENDER_DPI
              value: '600'
            - name: IMAGE_TESSERACT_LANG
              value: eng
            - name: IMAGE_UPSCALE_FACTOR
              value: '2.0'
            - name: INDEXING_PIPELINE_CPU_IMAGE_REPO
              value: athithya5354/indexing_pipeline_cpu
            - name: INDEXING_PIPELINE_CPU_IMAGE_TAG
              value: v7
            - name: JSONL_TARGET_TOKENS_PER_CHUNK
              value: '600'
            - name: LOG_LEVEL
              value: INFO
            - name: MANIFESTS_DIR
              value: infra/manifests/jobs
            - name: MAX_TOKENS_PER_CHUNK
              value: '320'
            - name: MIN_TOKENS_PER_CHUNK
              value: '100'
            - name: NAMESPACE
              value: indexing
            - name: NUMBER_OF_OVERLAPPING_SENTENCES
              value: '2'
            - name: OVERWRITE_ALL_AUDIO_FILES
              value: 'true'
            - name: OVERWRITE_DOC_DOCX_TO_PDF
              value: 'true'
            - name: OVERWRITE_PPT_WITH_PPTS
              value: 'true'
            - name: OVERWRITE_SPREADSHEETS_WITH_CSV
              value: 'true'
            - name: PDF_DISABLE_OCR
              value: 'false'
            - name: PDF_FORCE_OCR
              value: 'false'
            - name: PDF_MIN_IMG_SIZE_BYTES
              value: '3072'
            - name: PDF_OCR_ENGINE
              value: rapidocr
            - name: PDF_OCR_RENDER_DPI
              value: '400'
            - name: PDF_TESSERACT_LANG
              value: eng
            - name: PPTX_OCR_ENGINE
              value: rapidocr
            - name: PPTX_SLIDES_PER_CHUNK
              value: '4'
            - name: PYTHONUNBUFFERED
              value: '1'
            - name: QDRANT_API_KEY
              valueFrom:
                secretKeyRef:
                  name: qdrant-api-key
                  key: QDRANT_API_KEY
            - name: QDRANT_HNSW_EF_CONSTRUCT
              value: '128'
            - name: QDRANT_HNSW_FULL_SCAN_THRESHOLD
              value: '10000'
            - name: QDRANT_HNSW_M
              value: '32'
            - name: QDRANT_ONDISK
              value: 'TRUE'
            - name: QDRANT_SECRET_NAME
              value: qdrant-api-key
            - name: QDRANT_URL
              value: http://qdrant.qdrant.svc.cluster.local:6333
            - name: ROLEBINDING_NAME
              value: indexer-cron-rb
            - name: ROLE_NAME
              value: indexer-cron-role
            - name: SERVICE_ACCOUNT_NAME
              value: indexer-cron-sa
            - name: SPARSE_BATCH_FALLBACK
              value: '8'
            - name: SPARSE_URL
              value: http://sparse-svc.models.svc.cluster.local:8201
            - name: TESSERACT_CONFIG
              value: --oem 1 --psm 6
            - name: UAI_RAG_RO_CLIENT_ID
              value: ''
            - name: UAI_RAG_RO_NAME
              value: ''
            - name: UAI_RAG_RO_PRINCIPAL_ID
              value: ''
            - name: UAI_RAG_RW_CLIENT_ID
              value: ''
            - name: UAI_RAG_RW_NAME
              value: ''
            - name: UAI_RAG_RW_PRINCIPAL_ID
              value: ''
            - name: UPSERT_CHUNK
              value: '500'
            - name: USE_MANAGED_IDENTITY
              value: '0'
            resources:
              requests:
                cpu: '2'
                memory: 1Gi
              limits:
                cpu: '4'
                memory: 2Gi
      backoffLimit: 1
