apiVersion: v1
kind: Namespace
metadata:
  name: observability

---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  namespace: observability
spec:
  selector:
    app: clickhouse
  ports:
  - name: http
    port: 8123
    targetPort: 8123
  - name: tcp
    port: 9000
    targetPort: 9000
  - name: metrics
    port: 9116
    targetPort: 9116
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-exporter
  namespace: observability
spec:
  selector:
    app: clickhouse
  ports:
  - name: metrics
    port: 9116
    targetPort: 9116
  type: ClusterIP

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ch-single
  namespace: observability
spec:
  serviceName: clickhouse
  replicas: 1
  selector:
    matchLabels: &id001
      app: clickhouse
  template:
    metadata:
      labels: *id001
    spec:
      containers:
      - name: clickhouse
        image: clickhouse/clickhouse-server:23.12.6
        ports:
        - containerPort: 8123
          name: http
        - containerPort: 9000
          name: tcp
        volumeMounts:
        - name: data
          mountPath: /var/lib/clickhouse
        resources:
          requests:
            cpu: 250m
            memory: 1Gi
          limits:
            cpu: '1'
            memory: 2Gi
      - name: clickhouse-exporter
        image: flant/clickhouse-exporter:nightly-10102021
        args:
        - --scrape_uri=http://127.0.0.1:8123/
        - --telemetry.address=:9116
        ports:
        - containerPort: 9116
          name: metrics
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 128Mi
        startupProbe:
          httpGet:
            path: /
            port: 9116
          failureThreshold: 12
          periodSeconds: 5
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
