apiVersion: v1
kind: ServiceAccount
metadata:
  name: vm-agent-sa
  namespace: observability

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vm-agent-clusterrole
rules:
- apiGroups:
  - ''
  resources:
  - services
  - endpoints
  - pods
  - nodes
  - namespaces
  verbs:
  - get
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vm-agent-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: vm-agent-sa
  namespace: observability
roleRef:
  kind: ClusterRole
  name: vm-agent-clusterrole
  apiGroup: rbac.authorization.k8s.io
