apiVersion: v1
kind: ConfigMap
metadata:
  name: vmagent-scrape-config
  namespace: observability
data:
  prometheus.yml: "global:\n  scrape_interval: 15s\n  scrape_timeout: 10s\nscrape_configs:\n\
    - job_name: kubernetes-pods\n  kubernetes_sd_configs:\n  - namespaces:\n     \
    \ names: &id001\n      - inference\n      - qdrant\n      - observability\n  \
    \  role: pod\n  relabel_configs:\n  - action: keep\n    regex: 'true'\n    source_labels:\n\
    \    - __meta_kubernetes_pod_annotation_monitoring_io_scrape\n  - action: replace\n\
    \    regex: (.+);(.+)\n    replacement: $1:$2\n    source_labels:\n    - __meta_kubernetes_pod_ip\n\
    \    - __meta_kubernetes_pod_annotation_monitoring_io_port\n    target_label:\
    \ __address__\n  - source_labels:\n    - __meta_kubernetes_pod_name\n    target_label:\
    \ pod\n  - source_labels:\n    - __meta_kubernetes_namespace\n    target_label:\
    \ namespace\n  - source_labels:\n    - __meta_kubernetes_pod_container_name\n\
    \    target_label: container\n- job_name: kubernetes-services\n  kubernetes_sd_configs:\n\
    \  - namespaces:\n      names: *id001\n    role: service\n  relabel_configs:\n\
    \  - action: keep\n    regex: (true|True|1);?(.+)?\n    source_labels:\n    -\
    \ __meta_kubernetes_service_annotation_monitoring_io_scrape\n    - __meta_kubernetes_service_label_app_kubernetes_io_name\n\
    \  - source_labels:\n    - __meta_kubernetes_service_label_app_kubernetes_io_name\n\
    \    target_label: job\n  - action: replace\n    regex: metrics;(.*)\n    replacement:\
    \ $1\n    source_labels:\n    - __meta_kubernetes_service_port_name\n    - __meta_kubernetes_service_address\n\
    \    target_label: __address__\n"
