apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: qdrant-servicemonitor
  namespace: observability
  labels:
    app.kubernetes.io/managed-by: monitoring_and_alerts
spec:
  selector:
    matchLabels:
      app: qdrant
  namespaceSelector:
    matchNames:
    - observability
  endpoints:
  - port: http-metrics
    path: /metrics
    interval: 15s
