apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vmsingle
  namespace: observability
spec:
  serviceName: vmsingle
  replicas: 1
  selector:
    matchLabels: &id001
      app: vmsingle
  template:
    metadata:
      labels: *id001
    spec:
      containers:
      - name: vmsingle
        image: victoriametrics/victoria-metrics:v1.122.11
        imagePullPolicy: IfNotPresent
        args:
        - -storageDataPath=/victoria-metrics-data
        - -retentionPeriod=30d
        ports:
        - containerPort: 8428
          name: http
        volumeMounts:
        - name: data
          mountPath: /victoria-metrics-data
        livenessProbe:
          httpGet:
            path: /metrics
            port: 8428
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /metrics
            port: 8428
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: '1'
            memory: 2Gi
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
      volumes:
      - name: data
        emptyDir: {}
