apiVersion: v1
kind: Service
metadata:
  name: vmsingle
  namespace: observability
  labels:
    app: vmsingle
spec:
  selector:
    app: vmsingle
  ports:
  - protocol: TCP
    port: 8428
    targetPort: 8428
