apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmagent
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels: &id001
      app: vmagent
  template:
    metadata:
      labels: *id001
    spec:
      serviceAccountName: vm-agent-sa
      containers:
      - name: vmagent
        image: victoriametrics/vmagent:v1.122.11
        imagePullPolicy: IfNotPresent
        args:
        - -promscrape.config=/etc/vmagent/prometheus.yml
        - -remoteWrite.url=http://vmsingle.observability.svc.cluster.local:8428/api/v1/write
        - -remoteWrite.tmpDataPath=/vmagent-remotewrite-data
        - -remoteWrite.showURL=false
        volumeMounts:
        - name: vmagent-prom
          mountPath: /etc/vmagent
        livenessProbe:
          httpGet:
            path: /metrics
            port: 8429
          initialDelaySeconds: 20
          periodSeconds: 20
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /metrics
            port: 8429
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: '1'
            memory: 1Gi
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
      volumes:
      - name: vmagent-prom
        configMap:
          name: vmagent-scrape-config
