apiVersion: v1
kind: Service
metadata:
  name: vmagent
  namespace: observability
  labels:
    app: vmagent
spec:
  selector:
    app: vmagent
  ports:
  - name: metrics
    port: 8429
    targetPort: 8429
