grafana:
  enabled: true
  adminUser: admin
  adminPassword: change-me
  persistence:
    enabled: false
    size: 'false'
  nodeSelector: &id001
    observability: 'true'
  tolerations: &id002
  - key: CriticalAddonsOnly
    operator: Exists
    effect: NoSchedule
  securityContext:
    fsGroup: 472
  initChownData:
    enabled: false
prometheus:
  prometheusSpec:
    replicaCount: 1
    nodeSelector: *id001
    tolerations: *id002
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 500m
        memory: 1Gi
    storageSpec:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 5Gi
    retention: 7d
alertmanager:
  alertmanagerSpec:
    nodeSelector: *id001
    tolerations: *id002
nodeSelector: *id001
tolerations: *id002
