apiVersion: v1
kind: Secret
metadata:
  name: qdrant-backup-azure
  namespace: qdrant
type: Opaque
stringData:
  AZURE_STORAGE_CONNECTION_STRING: REPLACE_ME
  AZURE_STORAGE_ACCOUNT_NAME: REPLACE_ME
  AZURE_STORAGE_ACCOUNT_KEY: REPLACE_ME
