apiVersion: v1
kind: Secret
metadata:
  name: forward-auth-secret
  namespace: inference-auth
type: Opaque
stringData:
  jwt_secret: bUV7sP3kLM9aD44_QwZc8R_tNf2HjX
  session_secret: Zp4_tV9qLmA73sWf_Bg8Dh2_Ks0xRnE
