#!/usr/bin/env bash
# Minimal, idempotent cloudflared setup + DNS binding helper.
# - pinned to cloudflared behaviour used by 2025.11.1 (login, create, token, route dns)
# - always attempts DNS binding for FRONTEND_HOSTNAME, DASHBOARDS_HOSTNAME, EXTRA_HOSTNAMES
# - if DNS bind fails with origin-cert error, runs interactive `cloudflared tunnel login` then retries
set -euo pipefail

CLOUDFLARED_VERSION="${CLOUDFLARED_VERSION:-2025.11.1}"
INSTALL_BIN="${INSTALL_BIN:-/usr/local/bin/cloudflared}"
CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/rag"
SECRETS_FILE="${SECRETS_FILE:-${CONFIG_DIR}/secrets.env}"
TUNNEL_NAME="${CLOUDFLARE_TUNNEL_NAME:-rag-frontend}"
CLOUDLARED_HOME="${CLOUDLARED_HOME:-$HOME/.cloudflared}"
WAIT_SECONDS="${WAIT_SECONDS:-60}"

# DNS binding knobs
ENABLE_DNS_BINDING="${ENABLE_DNS_BINDING:-true}"
FRONTEND_HOSTNAME="${FRONTEND_HOSTNAME:-}"    # required
DASHBOARDS_HOSTNAME="${DASHBOARDS_HOSTNAME:-}"
EXTRA_HOSTNAMES="${EXTRA_HOSTNAMES:-}"        # comma-separated
DNS_OVERWRITE="${DNS_OVERWRITE:-true}"

PERSIST_SECRETS="${PERSIST_SECRETS:-true}"
SKIP_CERT_EXPORT="${SKIP_CERT_EXPORT:-false}"

mkdir -p "$CONFIG_DIR" "$CLOUDLARED_HOME"
chmod 700 "$CONFIG_DIR" 2>/dev/null || true
touch "$SECRETS_FILE" 2>/dev/null || true
chmod 600 "$SECRETS_FILE" 2>/dev/null || true

log(){ printf "%s INFO: %s\n" "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$1"; }
warn(){ printf "%s WARN: %s\n" "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$1" >&2; }
err(){ printf "%s ERROR: %s\n" "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$1" >&2; }

atomic_append_secret(){
  key="$1"; value="$2"
  if grep -q -E "^export ${key}=" "$SECRETS_FILE" 2>/dev/null; then
    log "secrets file already contains ${key}; leaving intact"
    return 0
  fi
  tmp="$(mktemp "${SECRETS_FILE}.tmp.XXXX")"
  printf 'export %s="%s"\n' "$key" "$value" > "$tmp"
  printf '\n# (autogenerated by cloudflared.sh)\n' >> "$tmp"
  cat "$tmp" >> "$SECRETS_FILE"
  rm -f "$tmp"
  chmod 600 "$SECRETS_FILE" 2>/dev/null || true
  log "persisted ${key} to ${SECRETS_FILE}"
}

b64_of(){
  f="$1"
  if [ ! -f "$f" ]; then printf ""; return 0; fi
  if base64 --help >/dev/null 2>&1 && base64 --help 2>&1 | grep -q -- '-w'; then
    base64 -w0 "$f" 2>/dev/null || true
  else
    base64 "$f" 2>/dev/null | tr -d '\n' || true
  fi
}

cf_run(){ cloudflared "$@" 2>&1 || true; }

ensure_cloudflared(){
  if command -v cloudflared >/dev/null 2>&1; then
    cur="$(cloudflared --version 2>/dev/null | head -n1 || true)"
    if echo "$cur" | grep -q "$CLOUDFLARED_VERSION"; then
      log "cloudflared present (matches ${CLOUDFLARED_VERSION})"
      return 0
    fi
    log "cloudflared present but version mismatch (${cur}); installing ${CLOUDFLARED_VERSION}"
  else
    log "cloudflared not found; installing ${CLOUDFLARED_VERSION}"
  fi
  tmp="$(mktemp /tmp/cloudflared.XXXX)"
  url="https://github.com/cloudflare/cloudflared/releases/download/${CLOUDFLARED_VERSION}/cloudflared-linux-amd64"
  if ! curl -fsSL -o "$tmp" "$url"; then
    warn "failed to download cloudflared; please install manually"
    rm -f "$tmp" || true
    return 1
  fi
  chmod +x "$tmp"
  if [ -w "$(dirname "$INSTALL_BIN")" ] || [ "$(id -u)" -eq 0 ]; then
    mv -f "$tmp" "$INSTALL_BIN"
  else
    if command -v sudo >/dev/null 2>&1; then
      sudo mv -f "$tmp" "$INSTALL_BIN"
    else
      warn "no permission to move binary to $INSTALL_BIN; leaving at $tmp (add to PATH)"
      return 1
    fi
  fi
  chmod 0755 "$INSTALL_BIN" || true
  log "installed cloudflared at ${INSTALL_BIN}"
}

get_tunnel_id(){
  name="$1"
  out="$(cf_run tunnel list --output json 2>/dev/null || true)"
  if [ -n "$out" ] && command -v jq >/dev/null 2>&1; then
    printf "%s" "$(printf "%s" "$out" | jq -r --arg n "$name" '.[]? | select(.name==$n) | .id' 2>/dev/null || true)"
    return
  fi
  out="$(cf_run tunnel list 2>/dev/null || true)"
  printf "%s" "$(printf "%s\n" "$out" | awk -v n="$name" '$0 ~ n {print $1; exit}' || true)"
}

create_tunnel_if_missing(){
  name="$1"
  tid="$(get_tunnel_id "$name")"
  if [ -n "$tid" ]; then
    log "found existing tunnel '${name}' (id=${tid})"
    printf "%s" "$tid"
    return
  fi
  log "creating tunnel '${name}' (interactive browser login may be required)"
  out="$(cf_run tunnel create "$name")"
  tid="$(printf "%s" "$out" | grep -Eo '[0-9a-fA-F\-]{36}' | head -n1 || true)"
  if [ -n "$tid" ]; then
    log "created tunnel '${name}' id=${tid}"
    printf "%s" "$tid"
    return
  fi
  warn "failed to create tunnel '${name}'"
  printf ""
}

generate_token_for_tunnel(){
  name="$1"
  out="$(cf_run tunnel token "$name")"
  tok="$(printf "%s" "$out" | tr -d '\r\n' | sed -n '1p' || true)"
  if printf "%s" "$tok" | grep -Eq '^[A-Za-z0-9+/=_-]{40,}$'; then
    printf "%s" "$tok"
  else
    printf ""
  fi
}

# attempt a single bind; return 0 on success
_attempt_bind(){
  tunnel="$1"; host="$2"
  if [ -z "$host" ]; then return 0; fi
  if [ "$DNS_OVERWRITE" = "true" ] || [ "$DNS_OVERWRITE" = "1" ]; then
    out="$(cf_run tunnel route dns --overwrite-dns "$tunnel" "$host")"
  else
    out="$(cf_run tunnel route dns "$tunnel" "$host")"
  fi
  printf "%s\n" "$out"
  # success messages include created/added/bound/already
  if printf "%s" "$out" | grep -iqE 'bound|created|added|already|exists'; then
    log "DNS binding reported ok for ${host}"
    return 0
  fi
  # detect documented origin-cert error and return 2 for that case
  if printf "%s" "$out" | grep -qiE 'Cannot determine default origin certificate path|Error locating origin cert|originCert'; then
    return 2
  fi
  return 1
}

bind_hostname_to_tunnel(){
  tunnel="$1"; host="$2"
  if [ -z "$host" ]; then return 0; fi
  # first quick detection whether host already appears in route list
  routes="$(cf_run tunnel route dns list 2>/dev/null || true)"
  if printf "%s" "$routes" | grep -q -F "$host"; then
    log "hostname ${host} already routed; skipping"
    return 0
  fi
  # attempt bind once normally
  _attempt_bind "$tunnel" "$host"
  rc=$?
  if [ $rc -eq 0 ]; then return 0; fi
  if [ $rc -eq 2 ]; then
    warn "binding attempt failed due to missing origin certificate; attempting interactive 'cloudflared tunnel login' to obtain cert.pem"
    # interactive login - user must complete in browser
    cloudflared tunnel login || true
    # wait briefly for cert to appear
    sleep 2
    # retry bind once more
    _attempt_bind "$tunnel" "$host"
    rc2=$?
    if [ $rc2 -eq 0 ]; then return 0; fi
    warn "bind attempt for ${host} still failed after interactive login"
    return 1
  fi
  warn "binding attempt for ${host} returned non-zero"
  return 1
}

# ---- main ----
ensure_cloudflared || true

# load persisted secrets (non-fatal)
if [ -f "$SECRETS_FILE" ]; then
  # shellcheck disable=SC1090
  . "$SECRETS_FILE" 2>/dev/null || true
fi

if [ -z "${FRONTEND_HOSTNAME:-}" ]; then
  err "FRONTEND_HOSTNAME must be set (e.g. ui.example.com)"
  exit 2
fi

TUNNEL_ID="$(get_tunnel_id "$TUNNEL_NAME" || true)"
if [ -z "$TUNNEL_ID" ]; then
  TUNNEL_ID="$(create_tunnel_if_missing "$TUNNEL_NAME" || true)"
fi
if [ -z "$TUNNEL_ID" ]; then
  warn "tunnel id not available for '${TUNNEL_NAME}'. Proceeding; some operations may fail."
else
  log "operating on tunnel ${TUNNEL_NAME} (id=${TUNNEL_ID})"
fi

TOKEN="$(generate_token_for_tunnel "$TUNNEL_NAME" || true)"
if [ -n "$TOKEN" ]; then
  export CLOUDFLARE_TUNNEL_TOKEN="$TOKEN"
  log "generated tunnel token (len=${#CLOUDFLARE_TUNNEL_TOKEN})"
  if [ "${PERSIST_SECRETS}" = "true" ] || [ "${PERSIST_SECRETS}" = "1" ]; then
    atomic_append_secret "CLOUDFLARE_TUNNEL_TOKEN" "$CLOUDFLARE_TUNNEL_TOKEN"
  fi
else
  warn "could not generate token; attempting credentials.json fallback"
  if [ -n "$TUNNEL_ID" ] && [ -f "${CLOUDLARED_HOME}/${TUNNEL_ID}.json" ] && [ "${SKIP_CERT_EXPORT}" != "true" ]; then
    B64="$(b64_of "${CLOUDLARED_HOME}/${TUNNEL_ID}.json")"
    if [ -n "$B64" ]; then
      export CLOUDFLARE_TUNNEL_CREDENTIALS_B64="$B64"
      if [ "${PERSIST_SECRETS}" = "true" ] || [ "${PERSIST_SECRETS}" = "1" ]; then
        atomic_append_secret "CLOUDFLARE_TUNNEL_CREDENTIALS_B64" "$CLOUDFLARE_TUNNEL_CREDENTIALS_B64"
      fi
      log "persisted base64(credentials.json) from ${CLOUDLARED_HOME}/${TUNNEL_ID}.json"
    fi
  fi
fi

# build hosts list
HOSTS=()
HOSTS+=("$FRONTEND_HOSTNAME")
if [ -n "${DASHBOARDS_HOSTNAME:-}" ]; then HOSTS+=("$DASHBOARDS_HOSTNAME"); fi
if [ -n "${EXTRA_HOSTNAMES:-}" ]; then
  IFS=',' read -r -a extra_arr <<< "$EXTRA_HOSTNAMES"
  for h in "${extra_arr[@]}"; do
    h_trim="$(printf "%s" "$h" | xargs)"
    if [ -n "$h_trim" ]; then HOSTS+=("$h_trim"); fi
  done
fi

if [ "${ENABLE_DNS_BINDING}" = "true" ] || [ "${ENABLE_DNS_BINDING}" = "1" ]; then
  for host in "${HOSTS[@]}"; do
    bind_hostname_to_tunnel "$TUNNEL_NAME" "$host" || warn "bind attempt for ${host} returned non-zero"
  done
else
  log "DNS binding disabled (ENABLE_DNS_BINDING=${ENABLE_DNS_BINDING}); skipping"
fi

# final summary
printf "\n%s SUMMARY:\n" "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
if [ -n "${CLOUDFLARE_TUNNEL_TOKEN:-}" ]; then
  printf "  CLOUDFLARE_TUNNEL_TOKEN length: %s\n" "${#CLOUDFLARE_TUNNEL_TOKEN}"
  printf "\nTo reuse in this shell:\n  export CLOUDFLARE_TUNNEL_TOKEN=\"%s\"\n\n" "$CLOUDFLARE_TUNNEL_TOKEN"
elif [ -n "${CLOUDFLARE_TUNNEL_CREDENTIALS_B64:-}" ]; then
  printf "  CLOUDFLARE_TUNNEL_CREDENTIALS_B64 present (base64 of credentials.json)\n\n"
else
  printf "  No token or credentials persisted. You must export CLOUDFLARE_TUNNEL_TOKEN or provide credentials.json in %s.\n" "$CLOUDLARED_HOME"
fi
printf "Persisted secrets file: %s (mode 600) [PERSIST_SECRETS=%s]\n" "$SECRETS_FILE" "$PERSIST_SECRETS"
log "done."
exit 0
