#!/usr/bin/env bash

# infra/setup/cloudflared-login-auto.sh
# Idempotent installer + interactive login helper + tunnel create + token exporter
# Produces either:
#  - CLOUDFLARE_TUNNEL_TOKEN (preferred), or
#  - CLOUDFLARE_TUNNEL_CREDENTIALS_B64 (fallback)
# Persists exports into $XDG_CONFIG_HOME/rag/secrets.env (mode 600).
# Safe to run repeatedly; non-destructive; no 'set -e' or 'exit' so caller controls failure behavior.

CLOUDFLARED_VERSION="${CLOUDFLARED_VERSION:-2025.11.1}"
INSTALL_BIN="${INSTALL_BIN:-/usr/local/bin/cloudflared}"
CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/rag"
SECRETS_FILE="${CONFIG_DIR}/secrets.env"
TUNNEL_NAME="${CLOUDFLARE_TUNNEL_NAME:-rag-frontend}"
CLOUDLARED_HOME="${HOME}/.cloudflared"
WAIT_SECONDS="${WAIT_SECONDS:-60}"
JQ_CMD="$(command -v jq 2>/dev/null || true)"

# Option 1 DNS binding knobs (opt-in)
ENABLE_DNS_BINDING="${ENABLE_DNS_BINDING:-"true"}"   # "true" to attempt cloudflared CLI DNS bind
PUBLIC_HOSTNAME="${FRONTEND_HOSTNAME:-"ui.athithya.site"}"   # e.g. ui.athithya.site
DNS_OVERWRITE="${DNS_OVERWRITE:-"true"}"             # "true" to pass --overwrite-dns (safe)

# Ensure directories exist with conservative permissions
mkdir -p "$CONFIG_DIR" 2>/dev/null || true
chmod 700 "$CONFIG_DIR" 2>/dev/null || true
mkdir -p "$CLOUDLARED_HOME" 2>/dev/null || true

# Load previously persisted secrets if present
if [ -f "$SECRETS_FILE" ]; then
  # shellcheck disable=SC1090
  . "$SECRETS_FILE" 2>/dev/null || true
fi

# Logging helpers
log() { printf "%s INFO: %s\n" "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$1"; }
warn() { printf "%s WARN: %s\n" "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$1" >&2; }

# Append export to secrets file idempotently (do not overwrite existing entries)
atomic_append_secret(){
  key="$1"
  value="$2"
  touch "$SECRETS_FILE" 2>/dev/null || true
  if grep -q -E "^export ${key}=" "$SECRETS_FILE" 2>/dev/null; then
    printf "%s INFO: secrets file already contains %s (leaving intact)\n" "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$key"
    return 0
  fi
  tmp="$(mktemp "${SECRETS_FILE}.tmp.XXXX")"
  printf 'export %s="%s"\n' "$key" "$value" > "$tmp"
  printf '\n# (autogenerated by cloudflared-login-auto.sh)\n' >> "$tmp"
  cat "$tmp" >> "$SECRETS_FILE"
  rm -f "$tmp" 2>/dev/null || true
  chmod 600 "$SECRETS_FILE" 2>/dev/null || true
  printf "%s INFO: persisted %s to %s\n" "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$key" "$SECRETS_FILE"
}

# Base64 helper for credentials.json fallback
b64_of(){
  f="$1"
  if [ ! -f "$f" ]; then
    printf ""
    return 0
  fi
  if base64 --help >/dev/null 2>&1 && base64 --help 2>&1 | grep -q -- '-w'; then
    base64 -w0 "$f" 2>/dev/null || true
  else
    base64 "$f" 2>/dev/null | tr -d '\n' || true
  fi
}

# If a token already exists in environment, print helpful reuse line and exit early
if [ -n "${CLOUDFLARE_TUNNEL_TOKEN:-}" ]; then
  printf "%s INFO: CLOUDFLARE_TUNNEL_TOKEN already present in environment (len=%s). To reuse in shell: . %s\n" "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "${#CLOUDFLARE_TUNNEL_TOKEN}" "$SECRETS_FILE"
  printf "export CLOUDFLARE_TUNNEL_TOKEN=\"%s\"\n" "$CLOUDFLARE_TUNNEL_TOKEN"
  return 0 2>/dev/null || true
fi

# Ensure cloudflared binary present (install pinned if missing or wrong version)
need_install=0
if command -v cloudflared >/dev/null 2>&1; then
  cur="$(cloudflared --version 2>/dev/null | head -n1 || true)"
  if echo "$cur" | grep -q "$CLOUDFLARED_VERSION"; then
    log "cloudflared present and matches pinned version: $CLOUDFLARED_VERSION"
  else
    log "cloudflared present but version mismatch ($cur). Will install pinned $CLOUDFLARED_VERSION."
    need_install=1
  fi
else
  log "cloudflared not found; will install pinned $CLOUDFLARED_VERSION."
  need_install=1
fi

if [ "$need_install" -eq 1 ]; then
  TMPDL="$(mktemp /tmp/cloudflared.XXXX)"
  URL="https://github.com/cloudflare/cloudflared/releases/download/${CLOUDFLARED_VERSION}/cloudflared-linux-amd64"
  log "Downloading cloudflared $CLOUDFLARED_VERSION from $URL"
  if curl -fsSL -o "$TMPDL" "$URL"; then
    chmod +x "$TMPDL" 2>/dev/null || true
    if [ -w "$(dirname "$INSTALL_BIN")" ] || [ "$(id -u)" -eq 0 ]; then
      mv -f "$TMPDL" "$INSTALL_BIN" 2>/dev/null || true
    else
      sudo mv -f "$TMPDL" "$INSTALL_BIN" 2>/dev/null || true
    fi
    chmod 0755 "$INSTALL_BIN" 2>/dev/null || true
    log "Installed cloudflared at $INSTALL_BIN"
  else
    warn "Failed to download cloudflared from $URL; please install manually and re-run script"
    rm -f "$TMPDL" 2>/dev/null || true
  fi
fi

# If not logged in, start interactive login and display the browser URL
if [ -f "${CLOUDLARED_HOME}/cert.pem" ]; then
  log "cloudflared account cert present at ${CLOUDLARED_HOME}/cert.pem"
else
  log "No cloudflared account cert found. Starting 'cloudflared tunnel login' (interactive browser required)."
  LOGIN_LOG="$(mktemp /tmp/cloudflared-login.XXXX.log)"
  cloudflared tunnel login >"$LOGIN_LOG" 2>&1 &
  LOGIN_PID=$!

  printed_url=0
  for i in $(seq 1 "$WAIT_SECONDS"); do
    sleep 1
    if [ -f "$LOGIN_LOG" ]; then
      url="$(grep -Eo 'https?://[^ )\"'\'']+' "$LOGIN_LOG" 2>/dev/null | grep -E 'dash.cloudflare.com|login.cloudflareaccess.org|trycloudflare' | head -n1 || true)"
      if [ -n "$url" ] && [ "$printed_url" -eq 0 ]; then
        printf "\n\n%s INFO: COMPLETE THESE STEPS IN YOUR BROWSER (within %ss):\n" "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$WAIT_SECONDS"
        printf "  1) Open the URL below (copy/paste into a browser).\n"
        printf "  2) Choose your Cloudflare account if prompted.\n"
        printf "  3) Select the correct zone and click AUTHORIZE.\n"
        printf "  4) Wait ~1-5s for cloudflared to download credentials to %s\n\n" "$CLOUDLARED_HOME"
        printf "Login URL:\n%s\n\n" "$url"
        printed_url=1
      fi
    fi
    if [ -f "${CLOUDLARED_HOME}/cert.pem" ]; then
      break
    fi
  done

  if [ -f "$LOGIN_LOG" ]; then
    printf "\n%s INFO: Last lines from cloudflared login log (for debugging):\n" "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    tail -n 20 "$LOGIN_LOG" 2>/dev/null || true
    rm -f "$LOGIN_LOG" 2>/dev/null || true
  fi

  if [ -f "${CLOUDLARED_HOME}/cert.pem" ]; then
    log "Account login succeeded; cert found at ${CLOUDLARED_HOME}/cert.pem"
  else
    warn "Account login did not complete within $WAIT_SECONDS seconds."
    warn "If host is headless: run 'cloudflared tunnel login' on a machine with a browser, copy ~/.cloudflared/*.json into ${CLOUDLARED_HOME}, then re-run this script."
    log "You may re-run the script; it will resume creation/token steps once login is present."
  fi
fi

# List/create tunnel and attempt to generate token
TUNNEL_ID=""

if command -v cloudflared >/dev/null 2>&1; then

  # Try to find existing tunnel id (prefer JSON parsing when jq present)
  if [ -n "$JQ_CMD" ]; then
    TUNNEL_ID="$(cloudflared tunnel list --output json 2>&1 | jq -r --arg n "$TUNNEL_NAME" '.[]? | select(.name==$n) | .id' 2>/dev/null || true)"
  else
    TUNNEL_ID="$(cloudflared tunnel list 2>&1 | awk -v n="$TUNNEL_NAME" '$0 ~ n {print $1; exit}' || true)"
  fi

  if [ -n "$TUNNEL_ID" ]; then
    log "Found existing tunnel '$TUNNEL_NAME' (id=$TUNNEL_ID)"
  else
    log "Tunnel '$TUNNEL_NAME' not found; attempting to create it now."

    # Record pre-existing credentials files to detect new file created by CLI
    pre_files="$(ls -1 "${CLOUDLARED_HOME}"/*.json 2>/dev/null || true)"

    # IMPORTANT: do NOT pass unsupported --output json to 'tunnel create'.
    # Some cloudflared versions treat that as a second arg and will fail.
    create_out="$(cloudflared tunnel create "$TUNNEL_NAME" 2>&1 || true)"
    printf "%s\n" "$create_out"

    # Attempt to extract UUID from the create output
    TUNNEL_ID="$(printf "%s\n" "$create_out" | grep -Eo '[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}' | head -n1 || true)"

    # If create did not print an id, detect a new credentials file in the config directory
    if [ -z "$TUNNEL_ID" ]; then
      post_files="$(ls -1 "${CLOUDLARED_HOME}"/*.json 2>/dev/null || true)"
      new_file=""
      for f in $post_files; do
        if ! printf "%s\n" "$pre_files" | grep -Fxq "$f" 2>/dev/null; then
          new_file="$f"
          break
        fi
      done
      if [ -n "$new_file" ] && [ -f "$new_file" ]; then
        TUNNEL_ID="$(basename "$new_file" .json)"
      fi
    fi

    # Last-resort: re-run list and parse (works if CLI updated remote state)
    if [ -z "$TUNNEL_ID" ] && [ -n "$JQ_CMD" ]; then
      TUNNEL_ID="$(cloudflared tunnel list --output json 2>&1 | jq -r --arg n "$TUNNEL_NAME" '.[]? | select(.name==$n) | .id' 2>/dev/null || true)"
    fi

    if [ -n "$TUNNEL_ID" ]; then
      log "Created tunnel '$TUNNEL_NAME' id=$TUNNEL_ID"
    else
      warn "Tunnel creation did not return an ID. This can happen if interactive login is required or account permissions prevented creation."
      log "Re-run this script after completing login (or create the tunnel manually in the Cloudflare dashboard)."
    fi
  fi

  # Attempt to generate a token (preferred). This will print token or an error message.
  if [ -n "$TUNNEL_NAME" ]; then
    token_out="$(cloudflared tunnel token "$TUNNEL_NAME" 2>&1 || true)"

    # If token looks like base64 / token characters, accept it
    if printf "%s\n" "$token_out" | grep -Eq '^[A-Za-z0-9+/=_-]+$'; then
      CLOUDFLARE_TUNNEL_TOKEN="$(printf "%s\n" "$token_out" | tr -d '\r\n')"
      export CLOUDFLARE_TUNNEL_TOKEN
      atomic_append_secret "CLOUDFLARE_TUNNEL_TOKEN" "$CLOUDFLARE_TUNNEL_TOKEN"
      log "Generated tunnel token for '$TUNNEL_NAME' (len=${#CLOUDFLARE_TUNNEL_TOKEN}). To reuse: export CLOUDFLARE_TUNNEL_TOKEN=... or source $SECRETS_FILE"
    else
      # No token; attempt to find and persist credentials.json (base64) as fallback
      creds_candidate=""
      if [ -n "$TUNNEL_ID" ] && [ -f "${CLOUDLARED_HOME}/${TUNNEL_ID}.json" ]; then
        creds_candidate="${CLOUDLARED_HOME}/${TUNNEL_ID}.json"
      else
        creds_candidate="$(ls -1 "${CLOUDLARED_HOME}"/*.json 2>/dev/null | head -n1 || true)"
      fi

      if [ -n "$creds_candidate" ] && [ -f "$creds_candidate" ]; then
        B64="$(b64_of "$creds_candidate")"
        if [ -n "$B64" ]; then
          CLOUDFLARE_TUNNEL_CREDENTIALS_B64="$B64"
          atomic_append_secret "CLOUDFLARE_TUNNEL_CREDENTIALS_B64" "$CLOUDFLARE_TUNNEL_CREDENTIALS_B64"
          log "Found credentials.json at $creds_candidate and persisted CLOUDFLARE_TUNNEL_CREDENTIALS_B64 to $SECRETS_FILE"
        else
          warn "Found credentials file but failed to base64 it: $creds_candidate"
        fi
      else
        warn "No token generated and no credentials.json found. If you completed interactive login, wait a few seconds and re-run this script."
      fi
    fi
  fi

  # === Option 1: Attempt DNS binding via cloudflared CLI (opt-in) ===
  if [ "${ENABLE_DNS_BINDING}" = "true" ]; then
    if [ -z "${PUBLIC_HOSTNAME}" ]; then
      warn "ENABLE_DNS_BINDING=true but PUBLIC_HOSTNAME not set; skipping DNS binding step."
    else
      log "DNS binding requested: attempting to bind ${PUBLIC_HOSTNAME} -> ${TUNNEL_NAME} (tunnel id=${TUNNEL_ID:-unknown}) using cloudflared CLI"
      if [ "${DNS_OVERWRITE}" = "true" ]; then
        log "DNS_OVERWRITE=true: will pass --overwrite-dns to cloudflared (safe)"
        route_cmd=(cloudflared tunnel route dns --overwrite-dns "$TUNNEL_NAME" "$PUBLIC_HOSTNAME")
      else
        route_cmd=(cloudflared tunnel route dns "$TUNNEL_NAME" "$PUBLIC_HOSTNAME")
      fi
      route_out="$("${route_cmd[@]}" 2>&1 || true)"
      printf "%s\n" "$route_out"
      # crude success detection: common positive words from cloudflared output
      if printf "%s\n" "$route_out" | grep -iqE 'added|created|success|already exists|record exists|Bound|bound'; then
        log "DNS binding command output indicates success or existing binding for ${PUBLIC_HOSTNAME}."
      else
        echo ""
      fi
    fi
  fi

else
  warn "cloudflared binary not available; cannot create/list tunnels. Install cloudflared and re-run."
fi

# Final summary with helpful reuse lines
printf "\n%s SUMMARY:\n" "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
if [ -n "${CLOUDFLARE_TUNNEL_TOKEN:-}" ]; then
  printf "  CLOUDFLARE_TUNNEL_TOKEN length: %s\n" "${#CLOUDFLARE_TUNNEL_TOKEN}"
  printf "\nTo reuse in this shell (copy-paste):\n  export CLOUDFLARE_TUNNEL_TOKEN=\"%s\"\n\n" "$CLOUDFLARE_TUNNEL_TOKEN"
else
  if [ -n "${CLOUDFLARE_TUNNEL_CREDENTIALS_B64:-}" ]; then
    printf "  CLOUDFLARE_TUNNEL_CREDENTIALS_B64 present (base64 of credentials.json)\n\nTo reuse in this shell (copy-paste):\n  export CLOUDFLARE_TUNNEL_CREDENTIALS_B64=\"%s\"\n\n" "$CLOUDFLARE_TUNNEL_CREDENTIALS_B64"
  else
    printf "  No token or credentials persisted. Complete the interactive login in your browser (see earlier messages) and re-run this script.\n"
  fi
fi

printf "Persisted secrets file: %s (mode 600)\n" "$SECRETS_FILE"
printf "%s INFO: Done.\n" "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
