apiVersion: v2
name: onnx-embedder
description: Helm chart for deploying the ONNX embedder-reranker RayService + frontend (CPU only).
type: application

# Chart (this chart) version — bump on any template/value change
version: 0.2.1
# Your app version (set to whatever you ship)
appVersion: "2.48.0"

# Pinned dependencies. These are DISABLED by default via .Values
# so the umbrella chart doesn't try to manage them unless you opt-in.
dependencies:
  - name: kuberay-operator
    version: "1.4.2" # pinned
    repository: "https://ray-project.github.io/kuberay-helm/"
    condition: kuberay-operator.enabled

  - name: kube-prometheus-stack
    version: "77.0.0" # pinned
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: prometheus.enabled

  - name: opentelemetry-collector
    version: "0.131.0" # pinned
    repository: "https://open-telemetry.github.io/opentelemetry-helm-charts"
    condition: opentelemetry-collector.enabled

  - name: traefik
    version: "37.0.0" # pinned (Traefik v3)
    repository: "https://traefik.github.io/charts"
    condition: ingress.controller.traefik.enabled

  - name: cert-manager
    version: "v1.18.2" # pinned
    repository: "https://charts.jetstack.io"
    condition: cert-manager.enabled

# Karpenter is no longer distributed on charts.karpenter.sh.
# Install from OCI via the script (optional, for EKS).
# - name: karpenter
#   version: "v1.4.0"
#   repository: "oci://ghcr.io/karpenter/karpenter"
#   condition: karpenter.enabled
